project:
  type: website
  output-dir: docs

website:
  title: "Francisca Castro"
  site-url: "https://francisca-castro.com"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - research.qmd
      - teaching.qmd
      
format:
  html:
    theme: solar
    css: bootstrap.min.css
    toc: true

editor: visual

