project:
  type: website
  output-dir: docs

website:
  title: "Francisca Castro"
  google-analytics: "G-0W2PBTWYQ6"
  site-url: "https://francisca-castro.com"
  page-footer:
    left: "Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/), by Francisca Castro"
    right: "[View the source at {{< fa brands github >}} GitHub](https://github.com/frcastrog/fcastro.github.io)"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - text: Research
        file: research/index.qmd
      - teaching.qmd
      
format:
  html:
    theme: solar
    css: bootstrap.min.css
    toc: true
    

editor: visual

