---
title: "Teaching"
---

### Humboldt-Universität zu Berlin

-   [Conflict in Latin America: A Century of Turmoil](Syllabus_LATAM_SoSe_2024.pdf) (Upcoming, Spring 2024)
-   Comparative Politics and International Relations (Undergraduate Seminar, Fall 2020-21, 2021-22, 2022-23, 2023-24)
-   [Collective Political Violence](Syllabus_CPV.pdf) (Undergraduate Seminar, Spring 2021 and 2023)

### Hertie School of Government (Teaching Assistant)

-   Statistics II (Spring 2023)
-   Statistics I (Fall 2021, Fall 2023)

### Pontificia Universidad Católica de Chile (Teaching Assistant)

-   Sociology of Public Opinion (Spring 2017)
-   Gender Studies (Fall 2016)
-   Methods for Social Sciences II (Spring 2016)
-   Political Sociology (Spring 2016)
-   Politics and Social Movements (Fall 2016)
-   Qualitative Method (Spring 2015)
-   Introduction to Political Theory (Fall 2013, 2014)
-   Formation and Development of Modern Society (Spring 2014)
-   Formation and Development of Modern Culture (Fall 2013, 2014)
