---
<<<<<<< HEAD
title: "The Mobilizing Potential of Mass Migration: Experimental Evidence from Honduras"
date: 2023-08-03
=======
title: "The mobilizing potential of mass migration: Experimental evidence from Honduras"
date: 2023-05-12
>>>>>>> e39137817e907ca7c1a07131bd098a558d1338ce
author:
  - name: Jesse Acevedo
    url: https://www.j-acevedo.com/
    orcid: 0000-0002-2897-6457
    affiliation: University of Denver
  - name: Francisca Castro
    url: https://francisca-castro.com
    orcid: 0000-0002-9547-0130
    affiliation: Humboldt-Universität zu Berlin
#categories:
#  - Human rights
#  - Civil society
#  - NGO regulations
#  - COVID-19
  
#pub-info:
#  reference:
#  links:
#    - name: PDF
#      url: acevedo-castro-honduras.pdf
#      local: true
#      icon: fa-solid fa-file-pdf
#    - name: Code
#      url: https://github.com/andrewheiss/covid-derogations
#      icon: fa-brands fa-github
#  extra: >-
#    Presented at a workshop on “The Implications of COVID-19 for Civic Spaces: Assessing Data, Patterns and Trends,” Leibniz-Institut Hessische Stiftung Friedens- und Konfliktforschung (HSFK), online, March 2021
pub-status: 
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
#   status: Under review
#   class: success
#   icon: fas fa-glasses
---

## Important links

-   {{< fa file-pdf >}} [Paper (preprint)](acevedo-castro-honduras_v2.pdf)
-   <i class="fa-brands fa-github"></i> [GitHub repository]()

## Abstract

<<<<<<< HEAD
Does mass emigration encourage or undermine protests? Emigration, being a personal decision made by households, can potentially aggregate into a collective expression of discontent against the prevailing status quo. In this paper, we focus on whether large-scale emigration influences protest support and participation. Using a survey experiment conducted in Honduras, we assess how emigration's salience affected public opinion about anti-government demonstrations in 2021. Our findings reveal that respondents primed with information about migration expressed more favorable opinions toward protests, although their participation in demonstrations was unaffected. This study contributes to a better understanding of the link between emigration and public opinion for those who stay in their origin country, and also its limitations to mobilizing for change during periods of political turmoil.
=======
Migrating can be a deeply personal and private decision made by individuals and their families. But when mass migration occurs, it can be an indicator of collective discontent and grievances. In fragile political settings, can mass migration also foster support for other manifestations of discontent, such as anti-government demonstrations? In this paper, we focus on whether the framing of migration as a private or public act influences support for and participation in protests. Using a survey experiment conducted in Honduras, we assess how the migrant caravan, framed as a public exit in the form of a caravan, affected public opinion about protests in 2021. We find that, when framed as a private act, migration produces protest support. This result is explained by the non-disruptive character of private migration. Our findings contribute to a better understanding of the circumstances under which migration serves as a safety valve to reduce dissidence, and when it has a backlash effect, fostering anti-government mobilization.
>>>>>>> e39137817e907ca7c1a07131bd098a558d1338ce

## BibTeX citation

``` bibtex
@unpublished{AcevedoCastro2023,
    Author = {Jesse Acevedo and Francisca Castro},
    Note = {Working paper},
<<<<<<< HEAD
    Title = {The Mobilizing Potential of Mass Migration: Experimental Evidence From Honduras},
=======
    Title = {The mobilizing potential of mass migration: Experimental evidence from Honduras},
>>>>>>> e39137817e907ca7c1a07131bd098a558d1338ce
    Year = {2023}}
```
