---
title: "Guerrilla Shadows on Gender: The Lingering Effects of the Peruvian Internal Armed Conflict on Women’s Political Aspirations"
date: 2025-09-21
author:
 - name: Francisca Castro
   url: https://francisca-castro.com
   orcid: 0000-0002-9547-0130
   affiliation: ISDC – International Security and Development Center, Berlin, Germany
#categories:
#  - Refugees
#  - Conflict exposure
#  - Environmental stress
#  - Social well-being
 
#pub-info:
#  reference: "HiCN Working Paper 431"
#  links:
#    - name: PDF
#      url: carrying-past-across-border.pdf
#      local: true
#      icon: fa-solid fa-file-pdf
#    - name: Code
#      url: https://github.com/frcastrog/syria-refugees-jordan
#      icon: <i class="fa-brands fa-github"></i>
#  extra: >-
pub-status: 
 status: Working Paper
 class: Working Paper
 icon: fa-solid fa-file-lines
---

## Important links

-   {{< fa file-pdf >}} [Paper (Working Paper Version)](Guerrilla_Shadows_on_Gender_250921.pdf)

## Abstract

How does political violence affect women's electoral aspirations? This study examines the impact of Peru's Internal Armed Conflict on women's political representation using Truth and Reconciliation Commission data combined with municipal electoral records from six election cycles (1980-1995). Employing TWFE models that exploit within-district temporal variation in violence exposure, I distinguish between recent violence and cumulative violence exposure since 1980. Results reveal that violence affects women's electoral success but not candidacy rates. Recent violence increases women's chances of winning office by 8.4 percentage points, while cumulative violence reduces electoral success by 3.3 percentage points. Effects vary significantly by perpetrator: Shining Path violence increases women's electoral prospects, while state violence shows negative effects. These patterns persist decades after the conflict ended, with only Shining Path violence legacies continuing to reduce women's political advancements through 2022, while state violence shows no lingering effects.

## BibTeX citation

``` bibtex
@unpublished{castro2025,
  title={Guerrilla Shadows on Gender: The Lingering Effects of the Peruvian Internal Armed Conflict on Women's Political Aspirations},
  author={Castro, Francisca},
  year={2025},
  note={Working paper}
}
```
