---
title: "Carrying the Past with you Across the Border: Long-term Effects of Conflict and Environmental Stress Exposure in Syria on the Social Well-being of Refugees in Jordan"
date: 2025-06-01
author:
 - name: Francisca Castro
   url: https://francisca-castro.com
   orcid: 0000-0002-9547-0130
   affiliation: ISDC – International Security and Development Center, Berlin, Germany; Humboldt-Universität zu Berlin
 - name: Tilman Brück
   affiliation: ISDC – International Security and Development Center, Berlin, Germany; Humboldt-Universität zu Berlin; Leibniz Institute of Vegetable and Ornamental Crops (IGZ), Großbeeren, Germany
   orcid: 0000-0002-8344-8948
 - name: Hadi Jaafar
   affiliation: American University of Beirut, Beirut, Lebanon
 - name: Wolfgang Stojetz
   affiliation: ISDC – International Security and Development Center, Berlin, Germany
#categories:
#  - Refugees
#  - Conflict exposure
#  - Environmental stress
#  - Social well-being
 
#pub-info:
#  reference: "HiCN Working Paper 431"
#  links:
#    - name: PDF
#      url: carrying-past-across-border.pdf
#      local: true
#      icon: fa-solid fa-file-pdf
#    - name: Code
#      url: https://github.com/frcastrog/syria-refugees-jordan
#      icon: <i class="fa-brands fa-github"></i>
#  extra: >-
pub-status: 
 status: Working Paper
 class: Working Paper
 icon: fa-solid fa-file-lines
---

## Important links
-   {{< fa file-pdf >}} [Paper (Working Paper Version)](https://hicn.org/wp-content/uploads/2025/06/HiCN-WP-431.pdf)

## Abstract

When refugees flee abroad, they carry the legacy of their traumatic experiences across borders. While there are over 43 million refugees worldwide, the long-term effects of conflict exposure on their well-being remain poorly understood. This paper examines how pre-displacement exposure to violent conflict and environmental stressors shapes the long-term social well-being of Syrian refugees in Jordan, focusing on life satisfaction, social trust, and social safety nets. Using representative survey data from refugees living in Jordan and conflict events, as well as remote sensing environmental data from Syria, we distinguish between exposure to conflict events and conflict fatalities, revealing distinct effects. While exposure to conflict events has no systematic impact on social outcomes, exposure to conflict fatalities significantly reduces life satisfaction and weakens social safety nets. These effects are critically mediated by mental health, with depressive symptoms significantly explaining the negative impact of conflict fatalities on life satisfaction. Our findings also highlight gendered dimensions: individuals living in female-majority households experience particularly severe declines in life satisfaction, whereas those in male-majority households show greater deterioration in social safety nets. Having experienced droughts before leaving Syria further amplifies the negative effects of conflict, particularly on social safety nets. These results highlight the importance of considering intersecting vulnerabilities due to gender, environmental stress, and conflict exposure when designing support systems for forcibly displaced populations.

## BibTeX citation

``` bibtex
@techreport{Castro2025refugees,
   Author = {Francisca Castro and Tilman Brück and Hadi Jaafar and Wolfgang Stojetz},
   Institution = {Households in Conflict Network (HiCN)},
   Number = {431},
   Title = {Carrying the Past with you Across the Border: Long-term Effects of Conflict and Environmental Stress Exposure in Syria on the Social Well-being of Refugees in Jordan},
   Type = {Working Paper},
   Year = {2025},
   Month = {June}}
```
