---
title: "Do Protests Change Voting Behavior? Electoral Trends in the Aftermath of Contention"
date: 2023-09-19
author:
  - name: Francisca Castro
    url: https://francisca-castro.com
    orcid: 0000-0002-9547-0130
    affiliation: Humboldt-Universität zu Berlin
  - name: Renata Retamal
    orcid: 0000-0001-7282-5122
    affiliation: Universidad de Chile
#categories:
#  - Human rights
#  - Civil society
#  - NGO regulations
#  - COVID-19
  
#pub-info:
#  reference:
#  links:
#    - name: PDF
#      url: acevedo-castro-honduras.pdf
#      local: true
#      icon: fa-solid fa-file-pdf
#    - name: Code
#      url: https://github.com/andrewheiss/covid-derogations
#      icon: <i class="fa-brands fa-github"></i>
#  extra: >-
Presented at MPSA 2022 and APSA 2022: 
pub-status: 
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
#   status: Under review
#   class: success
#   icon: fas fa-glasses
---

## Important links

-   {{< fa file-pdf >}} [Paper (preprint)](castro-retamal-bolivia.pdf)
-   <i class="fa-brands fa-github"></i> [GitHub repository]()

## Abstract

Can protests prompt changes in electoral behavior? In this paper, we examine variations in voter turnout and electoral preferences at the local level after a protest cycle. Using data on protest occurrence during the 2019 social mobilizations in Chile and Bolivia, we assess the impact that street demonstrations had on voting behavior in the elections that took place in the following year. Through a difference-in-differences design, we found that protests both increased turnout and changed electoral preferences. We argue that the rise in turnout is explained by the surge in political efficacy that emerged from the protests. Additionally, the protests generated a signaling effect, causing municipalities that had protests to vote for the incumbent party to a lesser extent. Our results reinforce the importance of protests on electoral behavior, not only because they mobilize people to vote, but also because they could potentially trigger electoral punishment towards the ruling party.

## BibTeX citation

``` bibtex
@unpublished{CastroRetamal2023,
    Author = {Francisca Castro and Renata Retamal},
    Note = {Working paper},
    Title = {Do protests change voting behavior? Electoral trends in the aftermath of contention},
    Year = {2023}}
```
